// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comments.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO notes_comments (id, comment, note_id, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, comment, note_id, created_at
`

type CreateCommentParams struct {
	ID        string
	Comment   string
	NoteID    string
	CreatedAt int64
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (NotesComment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.ID,
		arg.Comment,
		arg.NoteID,
		arg.CreatedAt,
	)
	var i NotesComment
	err := row.Scan(
		&i.ID,
		&i.Comment,
		&i.NoteID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :one
DELETE FROM notes_comments
WHERE id = ? AND note_id = ?
RETURNING id, comment, note_id, created_at
`

type DeleteCommentParams struct {
	ID     string
	NoteID string
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) (NotesComment, error) {
	row := q.db.QueryRowContext(ctx, deleteComment, arg.ID, arg.NoteID)
	var i NotesComment
	err := row.Scan(
		&i.ID,
		&i.Comment,
		&i.NoteID,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, comment, note_id, created_at FROM notes_comments
WHERE id = ?
`

func (q *Queries) GetCommentByID(ctx context.Context, id string) (NotesComment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i NotesComment
	err := row.Scan(
		&i.ID,
		&i.Comment,
		&i.NoteID,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByNoteID = `-- name: ListCommentsByNoteID :many
SELECT id, comment, note_id, created_at FROM notes_comments
WHERE note_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListCommentsByNoteID(ctx context.Context, noteID string) ([]NotesComment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByNoteID, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotesComment
	for rows.Next() {
		var i NotesComment
		if err := rows.Scan(
			&i.ID,
			&i.Comment,
			&i.NoteID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
