// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Note struct {
	ID        string
	Title     string
	Body      sql.NullString
	Priority  string
	Completed int64
	CreatedBy string
	CreatedAt int64
	UpdatedAt int64
}

type NotesComment struct {
	ID        string
	Comment   string
	NoteID    string
	CreatedAt int64
}

type Recipe struct {
	ID          string
	Title       string
	Description sql.NullString
	Tags        sql.NullString
	Ingredients sql.NullString
	Steps       sql.NullString
	ImageKey    sql.NullString
	CreatedAt   int64
	UpdatedAt   int64
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    int64
}

type WealthAccount struct {
	ID        string
	Name      string
	Type      string
	IsLiquid  int64
	IsClosed  int64
	UserID    string
	CreatedAt int64
}

type WealthAccountValue struct {
	ID        string
	AccountID string
	YearMonth string
	Value     int64
	CreatedAt int64
}
