// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    int64
}
