// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Recipe struct {
	ID          string
	Title       string
	Description sql.NullString
	Tags        sql.NullString
	Ingredients sql.NullString
	Steps       sql.NullString
	ImageKey    sql.NullString
	CreatedAt   int64
	UpdatedAt   int64
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Name         string
	CreatedAt    int64
}
