// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notes.sql

package db

import (
	"context"
	"database/sql"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (id, title, body, priority, completed, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, body, priority, completed, created_by, created_at, updated_at
`

type CreateNoteParams struct {
	ID        string
	Title     string
	Body      sql.NullString
	Priority  string
	Completed int64
	CreatedBy string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Priority,
		arg.Completed,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Priority,
		&i.Completed,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :one
DELETE FROM notes
WHERE id = ? AND created_by = ?
RETURNING id, title, body, priority, completed, created_by, created_at, updated_at
`

type DeleteNoteParams struct {
	ID        string
	CreatedBy string
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, deleteNote, arg.ID, arg.CreatedBy)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Priority,
		&i.Completed,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, title, body, priority, completed, created_by, created_at, updated_at FROM notes
WHERE id = ? AND created_by = ?
`

type GetNoteByIDParams struct {
	ID        string
	CreatedBy string
}

func (q *Queries) GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNoteByID, arg.ID, arg.CreatedBy)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Priority,
		&i.Completed,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotesByCompletion = `-- name: ListNotesByCompletion :many
SELECT id, title, body, priority, completed, created_by, created_at, updated_at FROM notes
WHERE completed = ? AND created_by = ?
ORDER BY created_at DESC
`

type ListNotesByCompletionParams struct {
	Completed int64
	CreatedBy string
}

func (q *Queries) ListNotesByCompletion(ctx context.Context, arg ListNotesByCompletionParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotesByCompletion, arg.Completed, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Priority,
			&i.Completed,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET title = ?, body = ?, priority = ?, completed = ?, updated_at = ?
WHERE id = ? AND created_by = ?
RETURNING id, title, body, priority, completed, created_by, created_at, updated_at
`

type UpdateNoteParams struct {
	Title     string
	Body      sql.NullString
	Priority  string
	Completed int64
	UpdatedAt int64
	ID        string
	CreatedBy string
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.Title,
		arg.Body,
		arg.Priority,
		arg.Completed,
		arg.UpdatedAt,
		arg.ID,
		arg.CreatedBy,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Priority,
		&i.Completed,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
