// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (NotesComment, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, arg DeleteCommentParams) (NotesComment, error)
	DeleteNote(ctx context.Context, arg DeleteNoteParams) (Note, error)
	DeleteRecipe(ctx context.Context, id string) (Recipe, error)
	GetCommentByID(ctx context.Context, id string) (NotesComment, error)
	GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (Note, error)
	GetRecipe(ctx context.Context, id string) (Recipe, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListCommentsByNoteID(ctx context.Context, noteID string) ([]NotesComment, error)
	ListNotesByCompletion(ctx context.Context, arg ListNotesByCompletionParams) ([]Note, error)
	ListRecipes(ctx context.Context) ([]Recipe, error)
	ListRecipesByTag(ctx context.Context, dollar_1 sql.NullString) ([]Recipe, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserNameEmail(ctx context.Context, arg UpdateUserNameEmailParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
