// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: recipes.sql

package db

import (
	"context"
	"database/sql"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (id, title, description, tags, ingredients, steps, image_key, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, title, description, tags, ingredients, steps, image_key, created_at, updated_at
`

type CreateRecipeParams struct {
	ID          string
	Title       string
	Description sql.NullString
	Tags        sql.NullString
	Ingredients sql.NullString
	Steps       sql.NullString
	ImageKey    sql.NullString
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, createRecipe,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.Ingredients,
		arg.Steps,
		arg.ImageKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Ingredients,
		&i.Steps,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :one
DELETE FROM recipes WHERE id = ? RETURNING id, title, description, tags, ingredients, steps, image_key, created_at, updated_at
`

func (q *Queries) DeleteRecipe(ctx context.Context, id string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, deleteRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Ingredients,
		&i.Steps,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, title, description, tags, ingredients, steps, image_key, created_at, updated_at FROM recipes WHERE id = ?
`

func (q *Queries) GetRecipe(ctx context.Context, id string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Ingredients,
		&i.Steps,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, title, description, tags, ingredients, steps, image_key, created_at, updated_at FROM recipes WHERE 1=1 ORDER BY created_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.Ingredients,
			&i.Steps,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipesByTag = `-- name: ListRecipesByTag :many
SELECT id, title, description, tags, ingredients, steps, image_key, created_at, updated_at FROM recipes WHERE tags LIKE '%' || ? || '%' ORDER BY created_at DESC
`

func (q *Queries) ListRecipesByTag(ctx context.Context, dollar_1 sql.NullString) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipesByTag, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.Ingredients,
			&i.Steps,
			&i.ImageKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes
SET title = ?, description = ?, tags = ?, ingredients = ?, steps = ?, image_key = ?, updated_at = ?
WHERE id = ?
RETURNING id, title, description, tags, ingredients, steps, image_key, created_at, updated_at
`

type UpdateRecipeParams struct {
	Title       string
	Description sql.NullString
	Tags        sql.NullString
	Ingredients sql.NullString
	Steps       sql.NullString
	ImageKey    sql.NullString
	UpdatedAt   int64
	ID          string
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipe,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.Ingredients,
		arg.Steps,
		arg.ImageKey,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.Ingredients,
		&i.Steps,
		&i.ImageKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
