// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: wealth.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO wealth_accounts (id, name, type, is_liquid, is_closed, user_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, type, is_liquid, is_closed, user_id, created_at
`

type CreateAccountParams struct {
	ID        string
	Name      string
	Type      string
	IsLiquid  int64
	IsClosed  int64
	UserID    string
	CreatedAt int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (WealthAccount, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.IsLiquid,
		arg.IsClosed,
		arg.UserID,
		arg.CreatedAt,
	)
	var i WealthAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsLiquid,
		&i.IsClosed,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :one
DELETE FROM wealth_accounts
WHERE id = ? AND user_id = ?
RETURNING id, name, type, is_liquid, is_closed, user_id, created_at
`

type DeleteAccountParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (WealthAccount, error) {
	row := q.db.QueryRowContext(ctx, deleteAccount, arg.ID, arg.UserID)
	var i WealthAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsLiquid,
		&i.IsClosed,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, type, is_liquid, is_closed, user_id, created_at FROM wealth_accounts
WHERE id = ? AND user_id = ?
`

type GetAccountByIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetAccountByID(ctx context.Context, arg GetAccountByIDParams) (WealthAccount, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, arg.ID, arg.UserID)
	var i WealthAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsLiquid,
		&i.IsClosed,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getAllValuesForUser = `-- name: GetAllValuesForUser :many
SELECT wav.id, wav.account_id, wav.year_month, wav.value, wav.created_at FROM wealth_account_values wav
JOIN wealth_accounts wa ON wav.account_id = wa.id
WHERE wa.user_id = ?
ORDER BY wav.year_month
`

func (q *Queries) GetAllValuesForUser(ctx context.Context, userID string) ([]WealthAccountValue, error) {
	rows, err := q.db.QueryContext(ctx, getAllValuesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WealthAccountValue
	for rows.Next() {
		var i WealthAccountValue
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.YearMonth,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValueByAccountAndMonth = `-- name: GetValueByAccountAndMonth :one
SELECT wav.id, wav.account_id, wav.year_month, wav.value, wav.created_at FROM wealth_account_values wav
JOIN wealth_accounts wa ON wav.account_id = wa.id
WHERE wav.account_id = ? AND wav.year_month = ? AND wa.user_id = ?
`

type GetValueByAccountAndMonthParams struct {
	AccountID string
	YearMonth string
	UserID    string
}

func (q *Queries) GetValueByAccountAndMonth(ctx context.Context, arg GetValueByAccountAndMonthParams) (WealthAccountValue, error) {
	row := q.db.QueryRowContext(ctx, getValueByAccountAndMonth, arg.AccountID, arg.YearMonth, arg.UserID)
	var i WealthAccountValue
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.YearMonth,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const getValuesByAccountID = `-- name: GetValuesByAccountID :many
SELECT wav.id, wav.account_id, wav.year_month, wav.value, wav.created_at FROM wealth_account_values wav
JOIN wealth_accounts wa ON wav.account_id = wa.id
WHERE wav.account_id = ? AND wa.user_id = ?
ORDER BY wav.year_month
`

type GetValuesByAccountIDParams struct {
	AccountID string
	UserID    string
}

func (q *Queries) GetValuesByAccountID(ctx context.Context, arg GetValuesByAccountIDParams) ([]WealthAccountValue, error) {
	rows, err := q.db.QueryContext(ctx, getValuesByAccountID, arg.AccountID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WealthAccountValue
	for rows.Next() {
		var i WealthAccountValue
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.YearMonth,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, name, type, is_liquid, is_closed, user_id, created_at FROM wealth_accounts
WHERE user_id = ?
ORDER BY type, name
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID string) ([]WealthAccount, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WealthAccount
	for rows.Next() {
		var i WealthAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.IsLiquid,
			&i.IsClosed,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValuesByYearMonth = `-- name: ListValuesByYearMonth :many
SELECT wav.id, wav.account_id, wav.year_month, wav.value, wav.created_at FROM wealth_account_values wav
JOIN wealth_accounts wa ON wav.account_id = wa.id
WHERE wa.user_id = ? AND wav.year_month = ?
ORDER BY wa.type, wa.name
`

type ListValuesByYearMonthParams struct {
	UserID    string
	YearMonth string
}

func (q *Queries) ListValuesByYearMonth(ctx context.Context, arg ListValuesByYearMonthParams) ([]WealthAccountValue, error) {
	rows, err := q.db.QueryContext(ctx, listValuesByYearMonth, arg.UserID, arg.YearMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WealthAccountValue
	for rows.Next() {
		var i WealthAccountValue
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.YearMonth,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE wealth_accounts
SET name = ?, type = ?, is_liquid = ?, is_closed = ?
WHERE id = ? AND user_id = ?
RETURNING id, name, type, is_liquid, is_closed, user_id, created_at
`

type UpdateAccountParams struct {
	Name     string
	Type     string
	IsLiquid int64
	IsClosed int64
	ID       string
	UserID   string
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (WealthAccount, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.IsLiquid,
		arg.IsClosed,
		arg.ID,
		arg.UserID,
	)
	var i WealthAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsLiquid,
		&i.IsClosed,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertValue = `-- name: UpsertValue :one
INSERT INTO wealth_account_values (id, account_id, year_month, value, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(account_id, year_month) DO UPDATE SET value = excluded.value
RETURNING id, account_id, year_month, value, created_at
`

type UpsertValueParams struct {
	ID        string
	AccountID string
	YearMonth string
	Value     int64
	CreatedAt int64
}

func (q *Queries) UpsertValue(ctx context.Context, arg UpsertValueParams) (WealthAccountValue, error) {
	row := q.db.QueryRowContext(ctx, upsertValue,
		arg.ID,
		arg.AccountID,
		arg.YearMonth,
		arg.Value,
		arg.CreatedAt,
	)
	var i WealthAccountValue
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.YearMonth,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}
